In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns 
import warnings 
warnings.filterwarnings('ignore')
%matplotlib inline

In [2]:
from sklearn import datasets

In [3]:
d=datasets.load_iris()

In [4]:
d

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [5]:
dir(d)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [6]:
d.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [7]:
d.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [8]:
d.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
d.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [9]:
d1 = pd.DataFrame({'sepel length':d.data[:,0],
                    'sepal width':d.data[:,1],
                     'petal length':d.data[:,2],
                    'petal width':d.data[:,3],
                    'species':d.target})

In [10]:
d1

sepel length  sepal width  petal length  petal width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [11]:
d1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepel length  150 non-null    float64
 1   sepal width   150 non-null    float64
 2   petal length  150 non-null    float64
 3   petal width   150 non-null    float64
 4   species       150 non-null    int32  
dtypes: float64(4), int32(1)
memory usage: 5.4 KB


In [12]:
d1.describe().T

count      mean       std  min  25%   50%  75%  max
sepel length  150.0  5.843333  0.828066  4.3  5.1  5.80  6.4  7.9
sepal width   150.0  3.057333  0.435866  2.0  2.8  3.00  3.3  4.4
petal length  150.0  3.758000  1.765298  1.0  1.6  4.35  5.1  6.9
petal width   150.0  1.199333  0.762238  0.1  0.3  1.30  1.8  2.5
species       150.0  1.000000  0.819232  0.0  0.0  1.00  2.0  2.0

In [13]:
from sklearn.model_selection import train_test_split

In [16]:
x=d1.drop(['species'],axis=1)

In [17]:
x

sepel length  sepal width  petal length  petal width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [19]:
y=d1.species

In [20]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: species, Length: 150, dtype: int32

In [21]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=3)

## Logistic Regression

In [23]:
from sklearn.linear_model import LogisticRegression

In [24]:
model_lr=LogisticRegression()

In [25]:
model_lr.fit(x_train,y_train)

LogisticRegression()

In [26]:
model_lr.score(x_test,y_test)

0.9777777777777777

## Support Vector Modifier

In [27]:
from sklearn.svm import SVC

In [30]:
model_vm=SVC()

In [31]:
model_vm.fit(x_train,y_train)

SVC()

In [32]:
model_vm.score(x_test,y_test)

0.9777777777777777

## Random forest

In [33]:
from sklearn.ensemble import RandomForestClassifier

In [34]:
model_rf = RandomForestClassifier()

In [35]:
model_rf.fit(x_train,y_train)

RandomForestClassifier()

In [36]:
model_rf.score(x_test,y_test)

0.9555555555555556

## Decision Tree Classifier

In [37]:
from sklearn.tree import DecisionTreeClassifier

In [38]:
model_dt=DecisionTreeClassifier()

In [39]:
model_dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [40]:
model_dt.score(x_test,y_test)

0.9777777777777777

## K Fold Cross Validation

In [43]:
from sklearn.model_selection import *

In [44]:
model_kf=KFold(n_splits=3)

### Cross Validation LogisticRegression

In [55]:
LR=cross_val_score(LogisticRegression(),x,y,cv=3)

In [56]:
LR

array([0.98, 0.96, 0.98])

In [57]:
LR.mean()

0.9733333333333333

### Cross Validation SVC

In [58]:
SV=cross_val_score(SVC(),x,y,cv=3)

In [59]:
SV

array([0.96, 0.98, 0.94])

In [60]:
SV.mean()

0.96

### Cross Validation RandomForestClassifier

In [61]:
RF=cross_val_score(RandomForestClassifier(),x,y,cv=3)

In [62]:
RF

array([0.98, 0.94, 0.94])

In [63]:
RF.mean()

0.9533333333333333

### Cross Validation DecisionTreeClassifier

In [64]:
DT=cross_val_score(DecisionTreeClassifier(),x,y,cv=3)

In [65]:
DT

array([0.98, 0.92, 1.  ])

In [66]:
DT.mean()

0.9666666666666667

## StratifiedKfold

In [68]:
S_fold=StratifiedKFold(n_splits=3)

In [69]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [72]:
score_LR=[]
score_SVC=[]
score_RF=[]
score_DT=[]
for train_index,test_index in S_fold.split(d.data,d.target):
    x_train,x_test,y_train,y_test=d.data[train_index],d.data[test_index],d.target[train_index],d.target[test_index]
    score_LR.append(get_score(LogisticRegression(),x_train,x_test,y_train,y_test))
    score_SVC.append(get_score(SVC(),x_train,x_test,y_train,y_test))
    score_RF.append(get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test))
    score_DT.append(get_score(DecisionTreeClassifier(),x_train,x_test,y_train,y_test))

In [73]:
score_LR

[0.98, 0.96, 0.98]

In [78]:
np.mean(score_LR)

0.9733333333333333

In [82]:
type(score_LR)

list

In [74]:
score_SVC

[0.96, 0.98, 0.94]

In [79]:
np.mean(score_SVC)

0.96

In [83]:
type(score_SVC)

list

In [75]:
score_RF

[0.98, 0.94, 0.96]

In [80]:
np.mean(score_RF)

0.96

In [84]:
type(score_RF)

list

In [76]:
score_DT

[0.98, 0.92, 0.96]

In [81]:
np.mean(score_DT)

0.9533333333333333

In [85]:
type(score_DT)

list