# 1) program to test whether none of the elements in a array is zero.

In [4]:
import numpy as np
x = np.array([1, 2, 3, 4])
print("array 1:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))
x = np.array([0, 1, 2, 3])
print("array 2:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))


array 1:
[1 2 3 4]
Test if none of the elements of the said array is zero:
True
array 2:
[0 1 2 3]
Test if none of the elements of the said array is zero:
False


# 2) program to test whether any of the elements in a array is non-zero.

In [5]:
x = np.array([1, 0, 0, 0])
print("array 1:")
print(x)
print("whether any of the elements in a array is non-zero:")
print(np.any(x))
x = np.array([0, 0, 0, 0])
print("array 2:")
print(x)
print("whether any of the elements in a array is non-zero:")
print(np.any(x))


array 1:
[1 0 0 0]
whether any of the elements in a array is non-zero:
True
array 2:
[0 0 0 0]
whether any of the elements in a array is non-zero:
False


# 3) Write a program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

In [12]:
X = np.array([1, 7, 13, 105])
print(X)
print("memory occupied by the array:")
print(X.itemsize*x.size,"bytes")


[  1   7  13 105]
memory occupied by the array:
16 bytes


# 4) Write a program to create an array of 10 zeros, 10 ones, 10 fives.

In [41]:
array1=np.zeros(10)
print(array1.astype(int))
array2=np.ones(10)
print(array2.astype(int))
array3=np.ones(10)*5
print(array3.astype(int))

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
[5 5 5 5 5 5 5 5 5 5]
